### PR TITLE
[UI-231] Update theme

### PR DESCRIPTION
**Pull request by George-Payne**
This PR updates our theme to match Kurrent branding, and changes some of the theme variables to match their usage while we're at it.

In packages that are affected by this, I've added demos where needed (which is the bulk of the code changes).

----

Theme variable name changes can be seen in: `packages/theme/src/types.ts`

Mapping between names are as follows:

| from                         | to                           |
| ---------------------------- | ---------------------------- |
| --color-background           | --color-background           |
| --color-contrast             | --color-foreground           |
| --color-text                 | --color-foreground           |
| --color-title-1              | --color-title                |
| --color-title-2              | --color-foreground           |
| --color-title-3              | --color-foreground           |
| --color-primary              | case by case                 |
| --color-primary-alt          | case by case                 |
| --color-primary-contrast     | case by case                 |
| --color-highlight            | case by case                 |
| --color-highlight-alt        | case by case                 |
| --color-highlight-contrast   | case by case                 |
| --color-secondary            | --color-highlight            |
| --color-secondary-alt        | case by case                 |
| --color-secondary-contrast   | --color-highlight-contrast   |
| --color-error                | --color-error                |
| --color-error-contrast       | --color-error-contrast       |
| --color-error-alt            | --color-error-alt            |
| --color-error-alt-contrast   | --color-error-alt-contrast   |
| --color-warning              | --color-warning              |
| --color-warning-contrast     | --color-warning-contrast     |
| --color-warning-alt          | --color-warning-alt          |
| --color-warning-alt-contrast | --color-warning-alt-contrast |
| --color-success              | --color-success              |
| --color-success-contrast     | --color-success-contrast     |
| --color-success-alt          | --color-success-alt          |
| --color-success-alt-contrast | --color-success-alt-contrast |
| --color-info                 | --color-info                 |
| --color-info-contrast        | --color-info-contrast        |
| --color-info-alt             | --color-info-alt             |
| --color-info-alt-contrast    | --color-info-alt-contrast    |
| --color-shade-10             | --color-shade-10             |
| --color-shade-20             | --color-shade-20             |
| --color-shade-30             | --color-shade-30             |
| --color-shade-40             | --color-shade-40             |
| --color-shade-50             | --color-shade-50             |
| --color-shade-60             | --color-shade-60             |
| --color-overlay              | --color-overlay              |
| --color-overlay-alpha        | --color-overlay-alpha        |
| --color-focus                | --color-focus                |
| --color-disabled             | --color-disabled             |
| --color-disabled-border      | --color-disabled-border      |
| --color-disabled-contrast    | --color-disabled-contrast    |

### CODE REVIEW

**Comment by teamchong** [comment]
image
image
image
image
I assume it’s intentional, but I’ve noticed that the disabled button has undergone quite a few changes in the new theme.

**Comment by teamchong** [comment]
Same for es-callout
image
image
image
image

**Review by teamchong — APPROVED** [review]
Look good a minor code formatting issue.

**Comment by George-Payne** [comment]
> I assume it’s intentional, but I’ve noticed that the disabled button has undergone quite a few changes in the new theme.

Ah, no it's not actually. I was looking at getting rid of the high contrast themes, and having a AAA contrast standard as default, but there were too many spots that would need to change, so I went back on the idea. I'll put them back.

> Same for es-callout

This one was intentional, the old design doesn't work with the new colours, and the design doesn't match with the new style anyway, so I simplified it, and made not to clean it up in [UI-241](https://eventstore-engineering.atlassian.net/browse/UI-241). I'll see if I can find something in the designs that map to it, or I'll speak to the designers, but it will get some cleanup before the feature branch is merged.

**Comment by George-Payne** [comment]
> @teamchong 
> I assume it’s intentional, but I’ve noticed that the disabled button has undergone quite a few changes in the new theme.

Ah, no it's not actually. I was looking at getting rid of the high contrast themes, and having a AAA contrast standard as default, but there were too many spots that would need to change, so I went back on the idea. I'll put them back.

> @teamchong 
> Same for es-callout

This one was intentional, the old design doesn't work with the new colours, and the design doesn't match with the new style anyway, so I simplified it, and made not to clean it up in [UI-241](https://eventstore-engineering.atlassian.net/browse/UI-241). I'll see if I can find something in the designs that map to it, or I'll speak to the designers, but it will get some cleanup before the feature branch is merged.

**Pull request merged**
